version: '2'

services:
  backend:
    build:
      context: .
      dockerfile: df.dev
    image: count:dev
    container_name: dev.backend
    environment:
      NODE_ENV: "development"
    volumes:
      - "./app:/home/count/app"
    ports:
      - "4567:4567"
      - "56745:56745"
    entrypoint: ["npm", "run", "debug"]    
