version: '2'
networks:
  de_db:
    driver: bridge

services:
  backend:
    build:
      dockerfile: df.prod
    extends: 
      file: dc.base.yml
      service: backend
    image: count:production
    container_name: ${APP_NAME}
    environment:
      NODE_ENV: "production"
    ports:
      - "${PORT}:4567"
    networks:
      - de_db
